### ISSUE TITLE
ReferenceError: check is not defined

### ISSUE THREAD

**Issue by emmanualojam** [bitomule/simple-metacrawler#6]
I really don't know if am doing something wrong or not, but my console is giving me the error "Exception while invoking method 'simplecrawler_findMetadata' ReferenceError: check is not defined", pls how can I fix this.

**Comment by bitomule** [comment]
You should install check. I forgot to include it as a dependency but should work if you add it manually: https://atmospherejs.com/meteor/check

Please confirm in it works so I can close the issue :)

**Comment by emmanualojam** [comment]
It fixed it, everything is fine now. Thank you.
